language: java
sudo: false
services:
- docker
jdk:
- oraclejdk8
install: true
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_e970b3decc70_key -iv $encrypted_e970b3decc70_iv -in gradle.properties.enc -out gradle.properties -d || true
script: ./gradle/buildViaTravis.sh
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- ./gradlew jacocoTestReport coveralls
